x-logging:
  &default-logging
  driver: json-file
  options:
    max-size: '100k'
    max-file: '2'

services:
  tg-repost:
    image: xtrime/telegram-api-server
    restart: unless-stopped
    init: true
    volumes:
      - ./:/app-host-link
    working_dir: /app-host-link
    depends_on:
      - mysql
    environment:
      WAIT_HOSTS: mysql:3306
    logging: *default-logging
  mysql:
    image: mariadb:11.0
    restart: unless-stopped
    ports:
      - "127.0.0.1:10306:3306"
    volumes:
      - ./.mysql:/var/lib/mysql
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 'yes'
      MARIADB_AUTO_UPGRADE: 'yes'
    command:
      - --innodb-buffer-pool-size=32M
      - --wait_timeout=65
      - --skip-grant-tables
    logging: *default-logging